### PR TITLE
Mark Video as Watched When Using External Player

### PR DESCRIPTION
**Pull request by jaruba**

### CODE REVIEW

**Review by TRtomasz — DISMISSED** [review]
seems to be working although not sure if i'm a fan of marking as watched right after you start playing something

**Comment by jaruba** [comment]
@TRtomasz there is no other option except marking it as watched immediately, any other case is error prone, maybe the user won't even go back to the web app and will close the entire browser, then it won't be marked as watched at all

**Comment by tymmesyde** [comment]
Tested and works, maybe we should also do that for the player feature ?
https://github.com/Stremio/stremio-web/blob/development/src/routes/Player/OptionsMenu/OptionsMenu.js#L56

And maybe it's better in that case to do that when we receive the event `PlayingOnDevice` from core instead of putting functions in each components: 
https://github.com/Stremio/stremio-web/blob/development/src/App/App.js#L97

**Comment by unclekingpin** [comment]
> Tested and works, maybe we should also do that for the player feature ? https://github.com/Stremio/stremio-web/blob/development/src/routes/Player/OptionsMenu/OptionsMenu.js#L56
> 
> And maybe it's better in that case to do that when we receive the event `PlayingOnDevice` from core instead of putting functions in each components: https://github.com/Stremio/stremio-web/blob/development/src/App/App.js#L97


That could be implemented within core itself

**Comment by TRtomasz** [comment]
@unclekingpin  does it require retesting? i see no logic has changed after your commits

**Comment by jaruba** [comment]
@TRtomasz we should always re-test for safety

**Review by TRtomasz — CHANGES_REQUESTED** [review]
hm, it works when opening in vlc but i no longer see option to mark it as watched/unwatched manually, i'm like 50% sure it was there before

**Comment by tymmesyde** [comment]
> hm, it works when opening in vlc but i no longer see option to mark it as watched/unwatched manually, i'm like 50% sure it was there before

This bug was introduced in a previous PR and only happens on Firefox, see #428

**Comment by jaruba** [comment]
@TRtomasz you mean this? https://github.com/Stremio/stremio-web/pull/418

**Comment by TRtomasz** [comment]
@jaruba  
image
 this, it is gone with this PR, couldn't open this menu
...
checked once again, yes context menu with this function is gone now

**Review by TRtomasz — DISMISSED** [review]
approving as context menu is fixed here https://github.com/Stremio/stremio-web/pull/428

**Comment by tymmesyde** [comment]
> > Tested and works, maybe we should also do that for the player feature ? https://github.com/Stremio/stremio-web/blob/development/src/routes/Player/OptionsMenu/OptionsMenu.js#L56
> > And maybe it's better in that case to do that when we receive the event `PlayingOnDevice` from core instead of putting functions in each components: https://github.com/Stremio/stremio-web/blob/development/src/App/App.js#L97
> 
> That could be implemented within core itself

The only way i can see this implemented easily in core is by passing the video id to the PlayOnDevice action as well, not sure if this is a good design since it has nothing to do with the streaming server

**Review by elpiel — APPROVED** [review]

**Pull request merged**
