### PR TITLE
Protect intro route

### LINKED ISSUE #328: Able to access login screen when already logged-in
## How to produce the bug

1. Login to your stremio account
2. go to https://web.stremio.com/#/intro
3. Login as guess

## Actual result
You're able to get to the login screen even though you're already logged in

## Expected result
You should be redirected to the home screen, you're authenticated after all

### PR DESCRIPTION
**Pull request by unclekingpin**

### CODE REVIEW

**Review by tymmesyde — COMMENTED** [review]
If a user refresh the page with a guest login, it will redirect to intro
Not sure how we can prevent that or if we want to
Other than that it works fine !

**Comment by TRtomasz** [comment]
working good, except the guest user redirection

**Comment by unclekingpin** [comment]
That will be fixed today. converting the PR into draft in the mean time.
cc: @TRtomasz @tymmesyde

**Comment by unclekingpin** [comment]
> That will be fixed today. converting the PR into draft in the mean time. cc: @TRtomasz @tymmesyde

ready for a review again.

**Review by tymmesyde — APPROVED** [review]

**Pull request merged**
