### PR TITLE
Fix search query handling to support multi-word queries

### PR DESCRIPTION
**Pull request by iAbhishekPanwar**
Changes Made:
Updated the URL construction logic to ensure the search query is captured accurately, including special characters and spaces. Ensured compatibility with all valid search query formats, avoiding malformed URLs.

Impact of the Fix:
Multi-word queries now work as expected, returning accurate and complete results. Improves the robustness of the URL handling logic.

Example:
Before the fix:

Searching "Alexa & Katie" would return results only for "Alexa."

After the fix:

The full query "Alexa & Katie" is correctly parsed, and results are returned for both "Alexa" and "Katie."

### CODE REVIEW

**Comment by kKaskak** [comment]
Hey. Thanks for the contribution, however the results were always correctly displayed. The issue was in the `SearchBar` component here 
https://github.com/Stremio/stremio-web/blob/development/src/common/NavBar/HorizontalNavBar/SearchBar/SearchBar.js#L64

where it should have been encoded with `encodeURIcomponent` function like this 

```
const searchValue = `/search?search=${encodeURIComponent(event.target.value)}`;
```

if you want you can make this change instead so we can merge your PR.

**Comment by iAbhishekPanwar** [comment]
Thanks for the reply, i'll make the change right away

**Comment by iAbhishekPanwar** [comment]
I’ve made the changes and opened a new PR with the fix.

**Comment by kKaskak** [comment]
> I’ve made the changes and opened a new PR with the fix.

Thank you will be reviewing the new PR then. 💯

**Pull request closed without merging**
