### PR TITLE
Explain how to configure yarn

### PR DESCRIPTION
**Pull request by Plecra**
The packages documentation is still having growing pains, and the syntax for .npmrc is hidden away quite well. This should make getting involved easier for contributors

### CODE REVIEW

**Comment by nklhtv** [comment]
Thank you for the PR, but there is no place for such a detailed explanation in every repository that uses gh packages. A single link to the github documentation is more than enough for everyone who cant search for it.

**Review by nklhtv — CHANGES_REQUESTED** [review]
Thank you for the PR, but there is no place for such a detailed explanation in every repository that uses gh packages. A single link to the github documentation is more than enough for everyone who cant search for it.

**Comment by Ivshti** [comment]
@Plecra I personally like the explanation but we're pushing for a way to get rid of needing this config altogether, so that this repo works with a simple `npm install`, so unfortunately we'll close this and perhaps re-open if we don't manage to make it not require config

**Comment by davidlondono** [comment]
wow really, I didn't know what was those Github Packages config, just found this merge useful and now the devs don't want it?
well you should consider to merge this or other links so you have a community to help you out

**Comment by Ivshti** [comment]
As I said, the intention is to make the GitHub Packages config **unneeded** as soon as possible, which is much better than having to explain it

**Pull request closed without merging**
